### ISSUE TITLE
Component rendering 4 times under react strict mode, when there is a usage of useSignals or similar in the component

### ISSUE THREAD

**Issue by ankitkaushik24** [XantreDev/preact-signals#200]
Following issue: https://github.com/XantreDev/preact-signals/issues/87

Although its closed, It's also worth noting that the issue is specific to strict mode, which is a feature in React that helps detect potential problems in an application. Disabling strict mode can help resolve the issue, but it's generally recommended to keep strict mode enabled in development to catch any potential issues.

Hence, I still believe its an issue to be resolved. I spent my entire day trying to figure out the unexplained re-renders initially in the strict mode.

**Comment by XantreDev** [comment]
Have you ever seen any useful hints from safe mode xD? In my case - I always turn it off, because of the unreliable `useEffect`-s

I don't consider this behavior a bug. I am working on SWC plugin compatible with `@preact/signals-react` runtime, there are chances it will have different set of problems, but I cannot say for sure

**Comment by XantreDev** [comment]
Sorry for the long response time
